services:
  - type: web
    name: road-pothole-detector
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      # Download SAM model if it doesn't exist
      if [ ! -f "$SAM_CHECKPOINT_PATH" ]; then
        curl -L "https://huggingface.co/lllyasviel/Annotators/resolve/main/sam_vit_b_01ec64.pth" -o "$SAM_CHECKPOINT_PATH"
      fi
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
      - key: DATA_DIR
        value: "/var/data/uploads"
      - key: SAM_CHECKPOINT_PATH
        value: "/var/data/sam_vit_b_01ec64.pth"
      - key: PYTHONPATH
        value: "."
    disk:
      name: pothole-data
      mountPath: /var/data
      sizeGB: 1