services:
  - type: web
    name: road-pothole-detector
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: pothole-data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
